DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS MPA CASCADE;
DROP TABLE IF EXISTS FILM CASCADE;
DROP TABLE IF EXISTS USER_FRIEND CASCADE;
DROP TABLE IF EXISTS LIKES_MOVIE CASCADE;
DROP TABLE IF EXISTS GENRE_FILM CASCADE;

CREATE TABLE if not exists USERS (
    user_id  INTEGER not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255) not null,
    login    varchar(255) not null,
    name     varchar(255),
    birthday date
  );

CREATE TABLE if not exists GENRE (
      genre_id INTEGER not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name_genre     varchar(255) not null
  );

CREATE TABLE if not exists MPA (
      mpa_id INTEGER not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name_mpa   varchar(255) not null
  );

CREATE TABLE if not exists FILM (
    film_id      INTEGER not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(255) not null,
    description  varchar(200) not null,
    release_date date not null,
    duration     int not null,
    rate       int,
    mpa_id       int references MPA(mpa_id)
);

CREATE TABLE if not exists USER_FRIEND (
    friend_id int not null references USERS(user_id),
    user_id   int not null references USERS(user_id),

    PRIMARY KEY(friend_id,user_id)
);

CREATE TABLE if not exists LIKES_MOVIE (
    film_id int not null references FILM(film_id),
    user_id int not null references USERS(user_id),

    PRIMARY KEY(film_id,user_id)
);

CREATE TABLE if not exists GENRE_FILM (
    genre_id int not null references GENRE(genre_id),
    film_id  int not null references FILM(film_id),

    PRIMARY KEY(genre_id,film_id)
);

